name: kindergarten_planner
description: Kindergarten Teacher Planner App
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"  # 升级到支持最新 Firebase 的 Dart 版本

dependencies:
  flutter:
    sdk: flutter
  # 核心状态管理
  provider: ^6.0.5
  # Firebase 系列（确保版本兼容）
  firebase_core: ^2.25.4       # 最新稳定版
  firebase_auth: ^4.17.4       # 与 firebase_core 匹配
  cloud_firestore: ^4.17.3     # 与 firebase_core 匹配
  # 聊天相关
  flutter_chat_types: ^3.6.2
  flutter_firebase_chat_core: ^1.6.1
  flutter_chat_ui: ^1.6.11
  # 其他功能
  table_calendar: ^3.0.8
  intl: ^0.18.1
  emoji_picker_flutter: ^1.5.0
  flutter_slidable: ^2.0.0
  pinput: ^2.2.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # 与最新 Dart 版本兼容