name: kindergarten_planner
description: Kindergarten Teacher Planner App
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"  # 适配 lints 2.x

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^2.15.1
  cloud_firestore: ^4.15.1
  firebase_auth: ^4.15.1
  flutter_chat_types: ^3.6.2
  flutter_firebase_chat_core: ^1.6.1
  table_calendar: ^3.0.8
  intl: ^0.18.1
  emoji_picker_flutter: ^1.5.0
  flutter_chat_ui: ^1.6.11
  flutter_slidable: ^2.0.0
  pinput: ^2.2.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1  # 兼容 Dart 2.x 的版本

# 强制 lints 版本（解决依赖冲突）
dependency_overrides:
  lints: 2.1.1